apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  namespace: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
      - name: nginx
        image: 192.168.50.50:5000/hello-nginx:v1
        ports:
        - containerPort: 80
